minimal_mistakes_skin    : "dark"  # 전체적인 색감 정의
                           # "default" "air", "aqua", "contrast", "dark"
                           # "dirt", "neon", "mint", "plum", "sunrise"
# 사이트 설정
locale                   : "ko-KR"    # 주요 언어 (한국어)
title                    : "나의 Github 포트폴리오"  # 사이트 메인에 보이는 이름입니다.
subtitle                 : "version 0.45"           # 화면 title 하단 소제목
name                     : "이성만(TREX99)"          # 화면 하단 영역의 이름
description              : "강의를 위한 준비 사이트"  # 화면 title 상단 소제목
url                      : "https://trex99.github.io" # 현재 url
baseurl                  : # 오류 발생시 이동할 url
repository               : "https://github.com/trex99/trex99.github.io" # Github 리포지토리 url
teaser                   : # 폴백일 때 보일 이미지입니다. "assets/images/"로 연결됩니다.
logo                     : "assets/images/trex.jpg"# logo 이미지
